"""Generates docs/asset_manifest.md from the Blender export manifests.

The Blender build scripts write one JSON per kit into art/exports/. This turns
those into the human-readable manifest the brief asks for, so the document can
never drift from what was actually exported.

Run:  python tools/make_asset_manifest.py
"""

import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORTS = os.path.join(REPO, "art", "exports")
OUT = os.path.join(REPO, "docs", "asset_manifest.md")

KITS = [
    ("hero_kit", "Hero kit", "tools/blender/build_hero.py",
     "The models that define the visual identity: the blue cannon, the faceted "
     "cannonball, the pip-faced dominoes, the window blocks, the yellow car and "
     "the celebration pieces."),
    ("world1_kit", "Triggers, ramps, targets and street dressing",
     "tools/blender/build_world1.py",
     "Buttons, plates, levers and springs; every ramp, platform and bridge; the "
     "final targets; and the World 1 street props."),
    ("reaction_kits", "Reaction kits", "tools/blender/build_kits.py",
     "Movers, mechanical parts, air and water, magnetic and electrical parts, "
     "destructibles with their debris, and the World 2-5 environment dressing."),
]

BUDGETS = [
    ("debris piece", 500),
    ("small prop", 2000),
    ("interactive object", 5000),
    ("large machine", 10000),
    ("environment landmark", 15000),
]


def main():
    lines = []
    lines.append("# Asset manifest\n")
    lines.append(
        "Every model in the game is generated by code in `tools/blender/` and "
        "exported to `assets/models/` as binary glTF. Delete `assets/models/` "
        "and re-run the three build scripts and you get the same geometry "
        "back — there are no hand-edited files in the pipeline.\n"
    )
    lines.append(
        "This document is generated by `tools/make_asset_manifest.py` from the "
        "export manifests the Blender scripts write, so it cannot drift from "
        "what was actually exported.\n"
    )

    all_entries = []
    kit_tables = []

    for slug, title, script, blurb in KITS:
        path = os.path.join(EXPORTS, f"{slug}.json")
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            entries = json.load(f)
        all_entries.extend(entries)

        rows = [
            f"\n## {title}\n",
            f"{blurb}\n",
            f"Source: `{script}` · Blender file: `art/blender/{slug}.blend`\n",
            "| Asset | Model path | Tris | Materials | Collider | Size (m, XYZ) | Purpose |",
            "| --- | --- | ---: | ---: | --- | --- | --- |",
        ]
        for e in sorted(entries, key=lambda x: x["slug"]):
            size = "x".join(f"{v:.3f}" for v in e["size"])
            rows.append(
                f"| `{e['slug']}` | `{e['path']}` | {e['tris']} | "
                f"{e['materials']} | {e['collider']} | {size} | {e['purpose']} |"
            )
        kit_tables.append("\n".join(rows))

    total_tris = sum(e["tris"] for e in all_entries)
    total_bytes = sum(e["bytes"] for e in all_entries)
    worst = max(all_entries, key=lambda e: e["tris"]) if all_entries else None

    lines.append("\n## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Models exported | **{len(all_entries)}** |")
    lines.append(f"| Total triangles | {total_tris:,} |")
    lines.append(f"| Total GLB size | {total_bytes / 1024:.0f} KB |")
    lines.append(f"| Mean triangles per model | {total_tris // max(1, len(all_entries))} |")
    if worst:
        lines.append(f"| Heaviest model | `{worst['slug']}` at {worst['tris']} tris |")
    lines.append(f"| Models over the 5,000-tri interactive budget | "
                 f"{sum(1 for e in all_entries if e['tris'] > 5000)} |")

    lines.append("\n### Triangle budgets\n")
    lines.append("| Class | Budget | Worst case in library |")
    lines.append("| --- | ---: | --- |")
    for name, budget in BUDGETS:
        over = [e for e in all_entries if e["tris"] > budget]
        note = "none over" if not over else f"{len(over)} over"
        lines.append(f"| {name} | {budget:,} | {note} |")

    lines.append("\n## Export settings\n")
    lines.append(
        "All models are exported with the same glTF settings, set in "
        "`tools/blender/toykit.py`:\n\n"
        "- **Format** — GLB (binary glTF 2.0), one file per asset\n"
        "- **Scale** — metric, 1 unit = 1 metre; toys are 0.05–1.2 m\n"
        "- **Transforms** — applied; every object's pivot is at its bounding-box "
        "centre so mesh and physics body agree\n"
        "- **Orientation** — Y-up conversion on; assets that have a forward face +X\n"
        "- **Materials** — exported as flat `baseColorFactor` only\n"
        "- **Normals, UVs, tangents, skins, morphs, animations, cameras, lights** "
        "— all off. The renderer shades per face from geometry, so normals in the "
        "file would be dead weight\n"
        "- **Shared accessors** — on\n"
    )

    lines.append(
        "\n## Colliders\n\n"
        "The `collider` column is the shape the runtime uses, not extra geometry "
        "in the file. `box` derives an oriented box from the model's bounding "
        "box; `sphere` uses the recorded radius; `cylinder` is approximated by a "
        "box; `none` means the model is visual only. A level can override any of "
        "these with an explicit `size` or `radius`.\n"
    )

    lines.extend(kit_tables)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {OUT}: {len(all_entries)} assets, {total_tris:,} tris")


if __name__ == "__main__":
    main()
